[tool.ruff]
line-length = 120
target-version = "py311"
exclude = [
    "migrations"
]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.isort]
section-order= ["future", "standard-library", "third-party", "flask-website", "local-folder"]
[tool.ruff.lint.isort.sections]
"flask-website" = ["db", "constants", "blocklist", "app", "resources", "models", "schemas", "utils"]


